### ISSUE TITLE
Add CI for Github Action

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/time-tracking#11]
So, when there are error in PR we can see, which part broke and make Web Apps error.  

similar issues / PR for CI Github Action is 
[PR Github Action](https://github.com/naufaldi/next-landing-vpn/pull/13)

**Comment by manojkrishnak** [comment]
Hi @naufaldi, assign this to me. 

You want CI on every PR by running `npm build` ?

**Comment by manojkrishnak** [comment]
#13 Have added github action file.
