### ISSUE TITLE
Create Better Component in ReactJS

### ISSUE THREAD

**Issue by naufaldi** [naufaldi/time-tracking#3]
every single file is on `pages/index.js` and this is not like how to think in reactjs. We should separate between component and page. So, make component base on how to think in reactJS and in `pages/index.js` , the content is just React Component and State. 

Make separate component and reusable components

- [x] #4
- [x] #5
- [x] #6
- [x] #7
- [x] #8
- [x] #9

at least, its the folder structure is like this
├── component   # all of component files 
│ ├── button # component button
│ ├── container # component for container
│ ├── input        # component for input
│ ├── Image  # component for image
└── README.md

**Comment by Rimjhim20** [comment]
Hey, @naufaldi  Can you assign me this issue? I'll make components.

**Comment by NishidhJain** [comment]
Hi @naufaldi I would like to work on this issue, please assign it to me

**Comment by naufaldi** [comment]
@NishidhJain @Rimjhim20 which part of component do you want to contribute?

**Comment by Rimjhim20** [comment]
I want to work on DarkImage and LightImage components. @naufaldi

**Comment by riansyh** [comment]
halo mas @naufaldi boleh assign issue Navbar component ke saya ga? makasih
